name: Build Sphinx docs

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build Sphinx docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setup markdown builder
        # run: pip3 install setuptools && pip3 install sphinx-markdown-builder
      - name: Doc html update
        uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -b html ./ ../../docs"
          docs-folder: "docsource/source"
      - name: Doc MD update
        uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -M markdown ./ ../../docs"
          docs-folder: "docsource/source"
          pre-build-command: "pip3 install setuptools && pip3 install sphinx-markdown-builder"
      - name: Move README and prepare docusaurus
        run: pwd && ls -l 
        # run: printf "\n\n" >> docs/markdown/README.md && mv docs/markdown/README.md README.md && cat README.md  docs/markdown/classes.md > docs/markdown/docusaurus.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: crisjf
          author_email: crisjf@mit.edu
          message: "Commit documentation changes"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
