# Description: Workflow that pulls all trained models from crisjf/NNNOMINATE
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: September 21, 2020

name: Pull models

on:
  schedule:
    - cron:  '0 0 * * *' # at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout NNNOMINATE
        uses: actions/checkout@v2
        with:
          repository: 'crisjf/NNNOMINATE'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: NNNOMINATE
      - name: Copy models
        run: cd main && pwd && ls -la && mkdir -p models/ && cp -r ../NNNOMINATE/results/models/ models/ && ls -la
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: crisjf
          author_email: crisjf@mit.edu
          message: "Models auto updated using action"
          add: "models/."
          cwd: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
